# The base go-image
FROM golang:1.19.4-alpine3.17
 
# Create a directory for the app
RUN mkdir /app
 
# Copy all files from the current directory to the app directory
WORKDIR /app

COPY . .
RUN go mod download
 
# Set working directory
 
# Run command as described:
# go build will build an executable file named server in the current directory
RUN go build -o /main
 
# Run the server executable
CMD [ "/main" ]